// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('/Users/akshayas/Documents/myreactnative/node_modules/react');
var { Component } = React;
var ReactNative = require('/Users/akshayas/Documents/myreactnative/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('myreactnative', appParameters);
});
require('/Users/akshayas/Documents/myreactnative/index.js');